DLauritz\WoW\GuildBundle\Entity\Guild:
  type: entity
  table: guilds
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    name:
      type: string
    realm:
      type: string
    last_modified:
      type: datetime
    battlegroup:
      type: string
    level:
      type: integer
    side:
      type: integer
    achievement_points:
      type: integer
    emblem_icon:
      type: integer
    emblem_icon_color:
      type: string
      length: 8
    emblem_border:
      type: integer
    emblem_border_color:
      type: string
      length: 8
    emblem_background_color:
      type: string
      length: 8
  oneToMany:
    members:
      targetEntity: Character
      mappedBy: guild
    news:
      targetEntity: NewsEvent
      mappedBy: guild
#    achievements:
#      targetEntity: AchievementStatus
#      mappedBy: guild