parameters:
#    d_lauritz_wo_w_guild.example.class: DLauritz\WoW\GuildBundle\Example

services:
#    d_lauritz_wo_w_guild.example:
#        class: %d_lauritz_wo_w_guild.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
